package com.kelsonthony.maratonajava.javacore.ZZGconcorrencia.test;

import com.kelsonthony.maratonajava.javacore.ZZGconcorrencia.dominio.Quote;
import com.kelsonthony.maratonajava.javacore.ZZGconcorrencia.service.StoreServiceWithDiscount;

import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.stream.Collectors;

public class CompletableFutureTest04 {
    public static void main(String[] args) {
        StoreServiceWithDiscount service = new StoreServiceWithDiscount();
        //searchPriceWithDiscount(service);
        searchPriceWithDiscountAsync(service);
    }
    private static void searchPriceWithDiscount(StoreServiceWithDiscount service) {
        long start = System.currentTimeMillis();
        List<String> stores = List.of("Store 1", "Store 2", "Store 3", "Store 4");

        //stores.forEach(s -> System.out.println(service.getPriceSync(s)));
        //store::price::code
        stores.stream()
                .map(service::getPriceSync)
                .map(Quote::newQuote)
                .map(service::applyDiscount)
                .forEach(System.out::println);

        long end = System.currentTimeMillis();

        System.out.printf("Time passed to searchPriceSync %dms%n", end - start);
    }

    private static void searchPriceWithDiscountAsync(StoreServiceWithDiscount service) {
        long start = System.currentTimeMillis();
        List<String> stores = List.of("Store 1", "Store 2", "Store 3", "Store 4");

        List<CompletableFuture<String>> completableFutures = stores.stream()
                //Getting the price async storeName:price:discountCode
                .map(s -> CompletableFuture.supplyAsync(() -> service.getPriceSync(s)))
                // Instantiating a Quote from the string generated by petPriceSync
                .map(cf -> cf.thenApply(Quote::newQuote))
                // Composing the first completable future
                .map(cf -> cf.thenCompose(quote -> CompletableFuture.supplyAsync(() -> service.applyDiscount(quote))))
                .collect(Collectors.toList());

        completableFutures.stream()
                .map(CompletableFuture::join)
                .forEach(System.out::println);

        long end = System.currentTimeMillis();

        System.out.printf("Time passed to searchPriceSync %dms%n", end - start);
    }
}
